import { useState } from 'react';
import { Link } from 'react-router-dom';
import PageBanner from '../components/PageBanner';
import Sidebar from '../components/Sidebar';
import bannerMacbook from '../assets/macbook-air-on-desk.jpg';

const FinancialCalculators = () => {
  const [openCategory, setOpenCategory] = useState('home');
  const [activeCalculator, setActiveCalculator] = useState({
    name: 'Comprehensive mortgage calculator',
    url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=hom03'
  });

  const categories = [
    {
      id: 'home',
      name: 'Home & Mortgage',
      calculators: [
        { name: 'Comprehensive mortgage calculator', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=hom03' },
        { name: 'Should I convert to a bi-weekly payment schedule?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=hom07' },
        { name: 'What are the tax savings generated by my mortgage?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=hom09' },
        { name: 'Compare an interest-only versus traditional mortgage', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=hom13' },
      ]
    },
    {
      id: 'auto',
      name: 'Auto',
      calculators: [
        { name: 'Auto purchase - Loan vs. 0% dealer financing?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=aut02' },
        { name: 'What would my auto payments be?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=aut03' },
        { name: 'Auto loan - Accelerated payoff', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=aut05' },
      ]
    },
    {
      id: 'retirement',
      name: 'Retirement',
      calculators: [
        { name: 'Social Security retirement income estimator', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=ret04' },
        { name: 'How does inflation impact my retirement income needs?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=ret05' },
        { name: 'Convert discretionary expenses to savings', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=ret08' },
      ]
    },
    {
      id: 'savings',
      name: 'Savings',
      calculators: [
        { name: 'Becoming a millionaire', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=sav01' },
        { name: 'How long will it take to double my money?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=sav03' },
        { name: 'How long until my savings reach my goal?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=sav04' },
        { name: 'Save now vs. save later', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=sav05' },
        { name: 'How much should I save to reach my goal?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=sav06' },
        { name: 'What will my current savings grow to?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=sav07' },
        { name: 'Calculate rate of return', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=sav08' },
        { name: 'How do taxes and inflation impact my return?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=sav09' },
      ]
    },
    {
      id: 'investment',
      name: 'Investment',
      calculators: [
        { name: 'Compare taxable vs. tax-free investment return', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=inv02' },
        { name: 'What is the value of a bond?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=inv03' },
        { name: 'What is the value of compound interest?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=inv05' },
        { name: 'What is the value of a call or put option?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=inv06' },
        { name: 'Taxable vs. tax-advantaged saving comparison', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=inv07' },
        { name: 'What is the long-term impact of increased return?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=inv09' },
        { name: 'Certificate of deposit (CD) analyzer', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=inv10' },
        { name: 'What is the dividend yield on a stock?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=inv11' },
        { name: 'How do expenses impact mutual fund returns?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=inv12' },
      ]
    },
    {
      id: 'debt',
      name: 'Credit & Debt',
      calculators: [
        { name: 'How long will it take to pay off my credit card(s)?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=det01' },
        { name: 'How long until my loan is paid off?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=det02' },
        { name: 'What would my loan payments be?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=det03' },
        { name: 'What is the balance owing on my loan?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=det05' },
        { name: 'Which is better, cash up front or payments over time?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=det08' },
        { name: 'Should I pay off debts or invest the money?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=det10' },
      ]
    },
    {
      id: 'tax',
      name: 'Taxation',
      calculators: [
        { name: 'Federal income tax estimator', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=inc02' },
        { name: 'How much self-employment tax will I pay?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=inc05' },
        { name: 'What is my taxable-equivalent yield?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=inc11' },
        { name: 'Tax refund estimator', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=inc12' },
        { name: 'Tax freedom day', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=inc13' },
      ]
    },
    {
      id: 'college',
      name: 'College',
      calculators: [
        { name: 'Will I be able to pay back my student loans?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=col02' },
        { name: 'Advantages of the Coverdell ESA', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=col03' },
        { name: 'Advantages of a 529 College Savings Plan', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=col04' },
        { name: 'What is the value of a college education?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=col05' },
        { name: 'What are the payments on a parental (PLUS) loan?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=col06' },
      ]
    },
    {
      id: 'insurance',
      name: 'Insurance',
      calculators: [
        { name: 'What is my life expectancy?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=ins02' },
        { name: 'What are the chances of becoming disabled?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=ins05' },
        { name: 'How much will I earn in my lifetime?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=ins07' },
        { name: 'What are the tax advantages of an annuity?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=ins08' },
        { name: 'How long will my current life insurance proceeds last?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=ins09' },
      ]
    },
    {
      id: 'cashflow',
      name: 'Cash Flow',
      calculators: [
        { name: 'Should I pay down debt or invest more?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=bud04' },
        { name: 'How long will my money last?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=bud05' },
        { name: 'Historical inflation - Compare purchasing power', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=bud12' },
      ]
    },
    {
      id: 'paycheck',
      name: 'Paycheck & Benefits',
      calculators: [
        { name: 'Convert my salary to an equivalent hourly wage', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=pay03' },
        { name: 'Convert my hourly wage to an equivalent salary', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=pay04' },
      ]
    },
    {
      id: 'business',
      name: 'Business',
      calculators: [
        { name: 'What are the tax savings of a qualified retirement/cafeteria plan?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=bus01' },
        { name: 'Should I pay or charge monthly, quarterly or annually?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=bus03' },
        { name: 'What is the value of my business?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=bus04' },
        { name: 'How many units do I need to sell to breakeven?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=bus05' },
        { name: 'Should I lease or buy equipment?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=bus06' },
        { name: 'What are my tax savings with Section 179 deduction?', url: 'https://www.calcxml.com/calculators/teaser-frame?calcId=bus09' },
      ]
    },
  ];

  const handleCalculatorSelect = (calc) => {
    setActiveCalculator(calc);
    window.scrollTo({ top: 350, behavior: 'smooth' });
  };

  return (
    <>
      <PageBanner
        title="Financial Calculators"
        backgroundImage={bannerMacbook}
      />
      <div className="page-content container">
        <div className="two-column">
          <div>
            <h2>Interactive Financial Planning Tools</h2>
            <p>
              Use our free financial calculators to help make informed decisions about your 
              finances. Select a category below, then choose a specific calculator.
            </p>

            {/* Category Buttons with Dropdowns */}
            <div style={{ marginBottom: '1.5rem' }}>
              {categories.map((category) => (
                <div key={category.id} style={{ marginBottom: '0.5rem' }}>
                  <button
                    onClick={() => setOpenCategory(openCategory === category.id ? null : category.id)}
                    style={{
                      width: '100%',
                      padding: '0.75rem 1rem',
                      border: 'none',
                      borderRadius: openCategory === category.id ? '8px 8px 0 0' : '8px',
                      backgroundColor: openCategory === category.id ? 'var(--primary-blue)' : 'var(--primary-navy)',
                      color: 'white',
                      cursor: 'pointer',
                      fontSize: '1rem',
                      fontWeight: '600',
                      textAlign: 'left',
                      display: 'flex',
                      justifyContent: 'space-between',
                      alignItems: 'center',
                      transition: 'all 0.2s ease'
                    }}
                  >
                    {category.name}
                    <span style={{ 
                      transform: openCategory === category.id ? 'rotate(180deg)' : 'rotate(0deg)',
                      transition: 'transform 0.2s ease'
                    }}>
                      ▼
                    </span>
                  </button>
                  {openCategory === category.id && (
                    <div style={{
                      backgroundColor: 'var(--off-white)',
                      border: '1px solid #ddd',
                      borderTop: 'none',
                      borderRadius: '0 0 8px 8px',
                      padding: '0.5rem'
                    }}>
                      {category.calculators.map((calc, index) => (
                        <button
                          key={index}
                          onClick={() => handleCalculatorSelect(calc)}
                          style={{
                            width: '100%',
                            padding: '0.6rem 1rem',
                            border: 'none',
                            borderRadius: '4px',
                            backgroundColor: activeCalculator.url === calc.url ? 'var(--secondary-cyan)' : 'transparent',
                            color: activeCalculator.url === calc.url ? 'white' : 'var(--text-dark)',
                            cursor: 'pointer',
                            fontSize: '0.9rem',
                            textAlign: 'left',
                            marginBottom: '0.25rem',
                            transition: 'all 0.2s ease'
                          }}
                          onMouseOver={(e) => {
                            if (activeCalculator.url !== calc.url) {
                              e.currentTarget.style.backgroundColor = '#e0e0e0';
                            }
                          }}
                          onMouseOut={(e) => {
                            if (activeCalculator.url !== calc.url) {
                              e.currentTarget.style.backgroundColor = 'transparent';
                            }
                          }}
                        >
                          {calc.name}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>

            {/* Active Calculator Display */}
            <div style={{
              backgroundColor: 'var(--white)',
              borderRadius: '8px',
              boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
              overflow: 'hidden',
              marginBottom: '2rem'
            }}>
              <div style={{
                backgroundColor: 'var(--primary-navy)',
                color: 'white',
                padding: '1rem 1.5rem',
              }}>
                <h3 style={{ margin: 0 }}>{activeCalculator.name}</h3>
              </div>
              <iframe
                src={activeCalculator.url}
                style={{
                  width: '100%',
                  height: '650px',
                  border: 'none'
                }}
                title={activeCalculator.name}
              />
            </div>

            <div style={{ 
              backgroundColor: 'var(--primary-navy)', 
              color: 'var(--white)', 
              padding: '2rem', 
              borderRadius: '8px', 
              marginTop: '2rem',
              textAlign: 'center'
            }}>
              <h3 style={{ marginTop: 0 }}>Need Help With Your Financial Planning?</h3>
              <p>
                Our team can help you interpret these results and develop a comprehensive 
                financial strategy tailored to your unique situation.
              </p>
              <Link to="/contact" className="btn btn-gold" style={{ marginRight: '1rem' }}>
                Contact Us
              </Link>
              <Link to="/book-meeting" className="btn btn-secondary">
                Schedule Consultation
              </Link>
            </div>
          </div>

          <Sidebar
            relatedPages={[
              { label: 'Tax Planning', path: '/tax-planning' },
              { label: 'Investment Strategies', path: '/investment-strategies' },
              { label: 'Retirement Planning', path: '/estate-planning' },
              { label: 'Business Advisory', path: '/business-advisory' },
            ]}
          />
        </div>
      </div>
    </>
  );
};

export default FinancialCalculators;
