import { useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import PageBanner from '../components/PageBanner';
import Sidebar from '../components/Sidebar';
import bannerMacbook from '../assets/macbook-air-on-desk.jpg';

const FinancialCalculators = () => {
  const [openCategory, setOpenCategory] = useState('home');
  const [activeCalculator, setActiveCalculator] = useState({
    name: 'Comprehensive mortgage calculator',
    calcId: 'hom03'
  });
  const [iframeHeight, setIframeHeight] = useState(450);
  const [iframeScale, setIframeScale] = useState(1.5);
  const containerRef = useRef(null);

  // Adjust iframe scale and height based on container width
  useEffect(() => {
    const updateDimensions = () => {
      if (containerRef.current) {
        const width = containerRef.current.offsetWidth;
        // Teaser calcs are ~340px wide, scale to fill container but not too much
        const scale = Math.min(1.8, Math.max(1.2, width / 380));
        setIframeScale(scale);
        // Adjust height based on scale (teaser calc is ~320px tall, add padding for submit)
        setIframeHeight(Math.min(550, 340 * scale));
      }
    };

    updateDimensions();
    window.addEventListener('resize', updateDimensions);
    return () => window.removeEventListener('resize', updateDimensions);
  }, []);

  // Brand colors for CalcXML customization (hex without #)
  const brandColor = '1a365d'; // primary-navy
  const textColor = 'ffffff'; // white

  // Build the embed URL with color customization
  const getCalcUrl = (calcId) => {
    return `https://www.calcxml.com/do/${calcId}?teaser&c=${brandColor}&tc=${textColor}`;
  };

  const categories = [
    {
      id: 'home',
      name: 'Home & Mortgage',
      calculators: [
        { name: 'Comprehensive mortgage calculator', calcId: 'hom03' },
        { name: 'Should I convert to a bi-weekly payment schedule?', calcId: 'hom07' },
        { name: 'What are the tax savings generated by my mortgage?', calcId: 'hom09' },
        { name: 'Compare an interest-only versus traditional mortgage', calcId: 'hom13' },
      ]
    },
    {
      id: 'auto',
      name: 'Auto',
      calculators: [
        { name: 'Auto purchase - Loan vs. 0% dealer financing?', calcId: 'aut02' },
        { name: 'What would my auto payments be?', calcId: 'aut03' },
        { name: 'Auto loan - Accelerated payoff', calcId: 'aut05' },
      ]
    },
    {
      id: 'retirement',
      name: 'Retirement',
      calculators: [
        { name: 'Social Security retirement income estimator', calcId: 'ret04' },
        { name: 'How does inflation impact my retirement income needs?', calcId: 'ret05' },
        { name: 'Convert discretionary expenses to savings', calcId: 'ret08' },
      ]
    },
    {
      id: 'savings',
      name: 'Savings',
      calculators: [
        { name: 'Becoming a millionaire', calcId: 'sav01' },
        { name: 'How long will it take to double my money?', calcId: 'sav03' },
        { name: 'How long until my savings reach my goal?', calcId: 'sav04' },
        { name: 'Save now vs. save later', calcId: 'sav05' },
        { name: 'How much should I save to reach my goal?', calcId: 'sav06' },
        { name: 'What will my current savings grow to?', calcId: 'sav07' },
        { name: 'Calculate rate of return', calcId: 'sav08' },
        { name: 'How do taxes and inflation impact my return?', calcId: 'sav09' },
      ]
    },
    {
      id: 'investment',
      name: 'Investment',
      calculators: [
        { name: 'Compare taxable vs. tax-free investment return', calcId: 'inv02' },
        { name: 'What is the value of a bond?', calcId: 'inv03' },
        { name: 'What is the value of compound interest?', calcId: 'inv05' },
        { name: 'What is the value of a call or put option?', calcId: 'inv06' },
        { name: 'Taxable vs. tax-advantaged saving comparison', calcId: 'inv07' },
        { name: 'What is the long-term impact of increased return?', calcId: 'inv09' },
        { name: 'Certificate of deposit (CD) analyzer', calcId: 'inv10' },
        { name: 'What is the dividend yield on a stock?', calcId: 'inv11' },
        { name: 'How do expenses impact mutual fund returns?', calcId: 'inv12' },
      ]
    },
    {
      id: 'debt',
      name: 'Credit & Debt',
      calculators: [
        { name: 'How long will it take to pay off my credit card(s)?', calcId: 'det01' },
        { name: 'How long until my loan is paid off?', calcId: 'det02' },
        { name: 'What would my loan payments be?', calcId: 'det03' },
        { name: 'What is the balance owing on my loan?', calcId: 'det05' },
        { name: 'Which is better, cash up front or payments over time?', calcId: 'det08' },
        { name: 'Should I pay off debts or invest the money?', calcId: 'det10' },
      ]
    },
    {
      id: 'tax',
      name: 'Taxation',
      calculators: [
        { name: 'Federal income tax estimator', calcId: 'inc02' },
        { name: 'How much self-employment tax will I pay?', calcId: 'inc05' },
        { name: 'What is my taxable-equivalent yield?', calcId: 'inc11' },
        { name: 'Tax refund estimator', calcId: 'inc12' },
        { name: 'Tax freedom day', calcId: 'inc13' },
      ]
    },
    {
      id: 'college',
      name: 'College',
      calculators: [
        { name: 'Will I be able to pay back my student loans?', calcId: 'col02' },
        { name: 'Advantages of the Coverdell ESA', calcId: 'col03' },
        { name: 'Advantages of a 529 College Savings Plan', calcId: 'col04' },
        { name: 'What is the value of a college education?', calcId: 'col05' },
        { name: 'What are the payments on a parental (PLUS) loan?', calcId: 'col06' },
      ]
    },
    {
      id: 'insurance',
      name: 'Insurance',
      calculators: [
        { name: 'What is my life expectancy?', calcId: 'ins02' },
        { name: 'What are the chances of becoming disabled?', calcId: 'ins05' },
        { name: 'How much will I earn in my lifetime?', calcId: 'ins07' },
        { name: 'What are the tax advantages of an annuity?', calcId: 'ins08' },
        { name: 'How long will my current life insurance proceeds last?', calcId: 'ins09' },
      ]
    },
    {
      id: 'cashflow',
      name: 'Cash Flow',
      calculators: [
        { name: 'Should I pay down debt or invest more?', calcId: 'bud04' },
        { name: 'How long will my money last?', calcId: 'bud05' },
        { name: 'Historical inflation - Compare purchasing power', calcId: 'bud12' },
      ]
    },
    {
      id: 'paycheck',
      name: 'Paycheck & Benefits',
      calculators: [
        { name: 'Convert my salary to an equivalent hourly wage', calcId: 'pay03' },
        { name: 'Convert my hourly wage to an equivalent salary', calcId: 'pay04' },
      ]
    },
    {
      id: 'business',
      name: 'Business',
      calculators: [
        { name: 'What are the tax savings of a qualified retirement/cafeteria plan?', calcId: 'bus01' },
        { name: 'Should I pay or charge monthly, quarterly or annually?', calcId: 'bus03' },
        { name: 'What is the value of my business?', calcId: 'bus04' },
        { name: 'How many units do I need to sell to breakeven?', calcId: 'bus05' },
        { name: 'Should I lease or buy equipment?', calcId: 'bus06' },
        { name: 'What are my tax savings with Section 179 deduction?', calcId: 'bus09' },
      ]
    },
  ];

  const handleCalculatorSelect = (calc) => {
    setActiveCalculator(calc);
    window.scrollTo({ top: 350, behavior: 'smooth' });
  };

  return (
    <>
      <PageBanner
        title="Financial Calculators"
        backgroundImage={bannerMacbook}
      />
      <div className="page-content container">
        <div className="two-column">
          <div>
            <h2>Interactive Financial Planning Tools</h2>
            <p>
              Use our free financial calculators to help make informed decisions about your 
              finances. Select a category below, then choose a specific calculator.
            </p>

            {/* Category Buttons with Dropdowns */}
            <div style={{ marginBottom: '1.5rem' }}>
              {categories.map((category) => (
                <div key={category.id} style={{ marginBottom: '0.5rem' }}>
                  <button
                    onClick={() => setOpenCategory(openCategory === category.id ? null : category.id)}
                    style={{
                      width: '100%',
                      padding: '0.75rem 1rem',
                      border: 'none',
                      borderRadius: openCategory === category.id ? '8px 8px 0 0' : '8px',
                      backgroundColor: openCategory === category.id ? 'var(--primary-blue)' : 'var(--primary-navy)',
                      color: 'white',
                      cursor: 'pointer',
                      fontSize: '1rem',
                      fontWeight: '600',
                      textAlign: 'left',
                      display: 'flex',
                      justifyContent: 'space-between',
                      alignItems: 'center',
                      transition: 'all 0.2s ease'
                    }}
                  >
                    {category.name}
                    <span style={{ 
                      transform: openCategory === category.id ? 'rotate(180deg)' : 'rotate(0deg)',
                      transition: 'transform 0.2s ease'
                    }}>
                      ▼
                    </span>
                  </button>
                  {openCategory === category.id && (
                    <div style={{
                      backgroundColor: 'var(--neutral-offwhite)',
                      border: '1px solid #ddd',
                      borderTop: 'none',
                      borderRadius: '0 0 8px 8px',
                      padding: '0.5rem'
                    }}>
                      {category.calculators.map((calc, index) => (
                        <button
                          key={index}
                          onClick={() => handleCalculatorSelect(calc)}
                          style={{
                            width: '100%',
                            padding: '0.6rem 1rem',
                            border: 'none',
                            borderRadius: '4px',
                            backgroundColor: activeCalculator.calcId === calc.calcId ? 'var(--secondary-cyan)' : 'transparent',
                            color: activeCalculator.calcId === calc.calcId ? 'white' : 'var(--text-dark)',
                            cursor: 'pointer',
                            fontSize: '0.9rem',
                            textAlign: 'left',
                            marginBottom: '0.25rem',
                            transition: 'all 0.2s ease'
                          }}
                          onMouseOver={(e) => {
                            if (activeCalculator.calcId !== calc.calcId) {
                              e.currentTarget.style.backgroundColor = '#e0e0e0';
                            }
                          }}
                          onMouseOut={(e) => {
                            if (activeCalculator.calcId !== calc.calcId) {
                              e.currentTarget.style.backgroundColor = 'transparent';
                            }
                          }}
                        >
                          {calc.name}
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>

            {/* Active Calculator Display */}
            <div 
              ref={containerRef}
              style={{
                backgroundColor: 'var(--white)',
                borderRadius: '8px',
                boxShadow: '0 4px 12px rgba(0,0,0,0.1)',
                overflow: 'hidden',
                marginBottom: '2rem'
              }}
            >
              <div style={{
                backgroundColor: 'var(--primary-navy)',
                color: 'white',
                padding: '1rem 1.5rem',
              }}>
                <h3 style={{ margin: 0, color: 'white' }}>{activeCalculator.name}</h3>
              </div>
              <div style={{
                overflow: 'hidden',
                height: `${iframeHeight}px`,
                position: 'relative'
              }}>
                <iframe
                  src={getCalcUrl(activeCalculator.calcId)}
                  style={{
                    width: `${100 / iframeScale}%`,
                    height: `${100 / iframeScale}%`,
                    border: 'none',
                    display: 'block',
                    transform: `scale(${iframeScale})`,
                    transformOrigin: 'top left'
                  }}
                  title={activeCalculator.name}
                  frameBorder="0"
                  scrolling="no"
                />
              </div>
              <div style={{
                padding: '0.5rem 1rem',
                backgroundColor: '#f5f5f5',
                borderTop: '1px solid #ddd',
                fontSize: '0.8rem',
                textAlign: 'center'
              }}>
                <a 
                  href="https://www.calcxml.com" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  style={{ color: 'var(--primary-navy)', textDecoration: 'none' }}
                >
                  Powered by CalcXML Financial Calculators
                </a>
              </div>
            </div>

            <div style={{ 
              backgroundColor: 'var(--primary-navy)', 
              color: 'var(--white)', 
              padding: '2rem', 
              borderRadius: '8px', 
              marginTop: '2rem',
              textAlign: 'center'
            }}>
              <h3 style={{ marginTop: 0, color: 'var(--white)' }}>Need Help With Your Financial Planning?</h3>
              <p style={{ color: 'var(--white)' }}>
                Our team can help you interpret these results and develop a comprehensive 
                financial strategy tailored to your unique situation.
              </p>
              <Link to="/contact" className="btn btn-gold" style={{ marginRight: '1rem' }}>
                Contact Us
              </Link>
              <Link to="/book-meeting" className="btn btn-secondary">
                Schedule Consultation
              </Link>
            </div>
          </div>

          <Sidebar
            relatedPages={[
              { label: 'Tax Planning', path: '/tax-planning' },
              { label: 'Investment Strategies', path: '/investment-strategies' },
              { label: 'Retirement Planning', path: '/estate-planning' },
              { label: 'Business Advisory', path: '/business-advisory' },
            ]}
          />
        </div>
      </div>
    </>
  );
};

export default FinancialCalculators;
